### PR TITLE
Add support for multi-part e-mail messages

### PR DESCRIPTION
**Pull request by grahammcculloch**
### Problem
Currently `django-fluent-comments` only supports plain text email notifications using the template `comments/comment_notification_email.txt`. It would be nice if it was possible to use multi-part (HTML) emails if desired.

### Solution

I've added a new template, `comments/comment_notification_email.html` which is just an HTML equivalent of the existing plain-text template. I've also updated the email-sending code to make use of this template, with the following consideration...

To ensure backwards compatibility and require 'buy-in' from the app user, multi-part emails are only sent if  the new setting `FLUENT_COMMENTS_MULTIPART_EMAILS` is set to `true`. By default this setting is `false` so that existing users don't find they're suddenly receiving HTML emails based on this new HTML template - rather than any overridden plain-text template they've created.

Example plain-text email:
exampleplaintextmessage

Example HTML email:
examplehtmlmessage

### CODE REVIEW

**Comment by vdboor** [comment]
Thanks a lot! this is a nice feature to have

**Comment by vdboor** [comment]
Do I think about renaming the setting to `FLUENT_COMMENTS_HTML_EMAIL=True` thoughts?

**Comment by vdboor** [comment]
I'm also fine with just enabling this, and adding it to the release notes that an HTML template should be implemented.

**Comment by grahammcculloch** [comment]
> Do I think about renaming the setting to FLUENT_COMMENTS_HTML_EMAIL=True thoughts?

IMHO you should only do this if you're going to bump the major version number. Otherwise users _will_ experience unexpected behavior when they upgrade. With a new major version number you can introduce this as a breaking change that will require some change in the user's code (either setting this value to false in their settings file or adding an HTML version of their custom email template).

**Pull request merged**
